### PR TITLE
feat: allowing only one like per user per comment

### PR DESCRIPTION
**Pull request by personalyisus**
Changed a bit the way that the likes were saved in the comments, since there should be a way to know if a user already liked a comment or not and the only way currently is to store which users did and then use the length of users who liked to determine how many likes a comment has

So to wrap it up: comment likes now are represented by an array of user IDs that have liked the comments. This solves #1 

Let me know if these changes seem ok to you @BoburCS  (:

### CODE REVIEW

**Comment by BoburCS** [comment]
wow! i really appreciete your help. i did not thought some will review and enhance my project lol

**Comment by personalyisus** [comment]
No problem! glad to contribute; you did put the "help wanted" tag so someone was bound to help eventually ;)

If I could give you a recommendation, I'd suggest using tools like prettier or eslint to format and keep your code consistent and neat

cheers!

**Comment by BoburCS** [comment]
thanks for recommendation)

**Comment by BoburCS** [comment]
how do your review others code? for me, its very hard. any suggestions??

**Pull request merged**
